// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfaoofthtpwniydaubyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYW9vZnRodHB3bml5ZGF1Ynl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzM4MzIsImV4cCI6MjA1NzIwOTgzMn0.ZXcpJF7dxFlHBwjtKLsgluSB8EiA4J2U8NCPlWgF1Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);